#!/usr/bin/env python3
import time
import colors as c
import random
to = input(c.orange + 'What number what you like to count to? ' + c.green)
to = int(to)

print(c.violet + 'Counting yeeey math ' + c.blue + str(to) + c.reset)
for count in range(to):
    time.sleep(1)
    print(c.clear)


answers = [
    c.blue + 'fluffy seconds' + c.reset,
    c.yellow + 'missisipi' + c.reset,
    c.red + 'yellow sheep' + c.reset
]


while True:
    answer = random.choice(answers)
    print(str(count + 1) + answer)
