#!/usr/bin/env python3
import time
import colors as c
to = input(c.orange + 'What number what you like to count to? ' + c.green)
to = int(to)

print(c.violet + 'Counting yeeey math ' + c.blue + str(to) + c.reset)
for count in range(to):
    time.sleep(1)
    print(c.clear)
    print(c.red + str(count + 1) + c.magenta + "fluffy seconds")
